import { useState, useEffect } from 'react';
import api from '@/lib/axios';
import { AdminAuditLogItem } from '@/types/admin-audit';

let cachedSuperAdminIdentifiers: Set<string> | null = null;
let cacheExpiry = 0;
let inflightFetch: Promise<Set<string>> | null = null;

/**
 * Dynamically fetches all SuperAdmin identifiers (userIds, emails, displayNames, userNames)
 * from the Admin Users directory without hardcoding any user details.
 * Deduplicates concurrent requests and caches in-memory.
 */
export async function fetchSuperAdminIdentifiers(forceRefresh = false): Promise<Set<string>> {
  const now = Date.now();
  if (!forceRefresh && cachedSuperAdminIdentifiers && now < cacheExpiry) {
    return cachedSuperAdminIdentifiers;
  }

  if (inflightFetch) {
    return inflightFetch;
  }

  inflightFetch = (async () => {
    try {
      const res = await api.get('/admin/users', {
        params: { role: 'SuperAdmin', pageSize: 100 },
      });

      const items: Array<{
        userId?: string;
        email?: string;
        displayName?: string;
        userName?: string;
      }> = res.data?.items || [];

      const set = new Set<string>();
      for (const item of items) {
        if (item.userId) set.add(item.userId.trim().toLowerCase());
        if (item.email) set.add(item.email.trim().toLowerCase());
        if (item.displayName) set.add(item.displayName.trim().toLowerCase());
        if (item.userName) set.add(item.userName.trim().toLowerCase());
      }

      cachedSuperAdminIdentifiers = set;
      cacheExpiry = Date.now() + 60 * 1000; // 1 minute cache
      return set;
    } catch {
      return cachedSuperAdminIdentifiers || new Set<string>();
    } finally {
      inflightFetch = null;
    }
  })();

  return inflightFetch;
}

/**
 * Determines whether an audit log entry was generated by a SuperAdmin actor
 * using explicit role metadata, action prefixes, or dynamic actor identity resolution.
 */
export function isPrivilegedAuditActor(
  log: AdminAuditLogItem | null | undefined,
  superAdminIdentifiers?: Set<string> | null
): boolean {
  if (!log) return false;

  // 1. Direct role attributes on the log item (if present)
  const directRole = (log as any).actorRole || (log as any).role;
  if (directRole && String(directRole).trim().toLowerCase() === 'superadmin') {
    return true;
  }

  const directRoles: any = (log as any).actorRoles || (log as any).roles;
  if (Array.isArray(directRoles) && directRoles.some((r) => String(r).trim().toLowerCase() === 'superadmin')) {
    return true;
  }

  // 2. Structured details payload role metadata
  if (log.details && typeof log.details === 'object') {
    const detailRole = log.details.role || log.details.actorRole;
    if (detailRole && String(detailRole).trim().toLowerCase() === 'superadmin') {
      return true;
    }

    const detailRoles = log.details.roles || log.details.actorRoles;
    if (Array.isArray(detailRoles) && detailRoles.some((r) => String(r).trim().toLowerCase() === 'superadmin')) {
      return true;
    }
  }

  // 3. SuperAdmin-specific action namespace
  if (log.action && String(log.action).trim().toLowerCase().startsWith('superadmin_')) {
    return true;
  }

  // 4. Dynamic SuperAdmin identifier lookup (actor email / userId / name)
  if (superAdminIdentifiers && superAdminIdentifiers.size > 0) {
    if (log.actor && superAdminIdentifiers.has(log.actor.trim().toLowerCase())) {
      return true;
    }
    if (log.details && typeof log.details === 'object') {
      const detailActorUserId = log.details.actorUserId || log.details.userId;
      if (detailActorUserId && superAdminIdentifiers.has(String(detailActorUserId).trim().toLowerCase())) {
        return true;
      }
      const detailActorEmail = log.details.actorEmail || log.details.email;
      if (detailActorEmail && superAdminIdentifiers.has(String(detailActorEmail).trim().toLowerCase())) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Filters audit logs according to viewer authority.
 * SuperAdmin sees all logs. Normal Admin sees only non-privileged logs.
 */
export function filterVisibleAuditLogs(
  logs: AdminAuditLogItem[],
  canSeePrivileged: boolean,
  superAdminIdentifiers?: Set<string> | null
): AdminAuditLogItem[] {
  if (canSeePrivileged) {
    return logs;
  }
  return logs.filter((log) => !isPrivilegedAuditActor(log, superAdminIdentifiers));
}

/**
 * React hook to supply dynamic SuperAdmin identifiers for normal Admin audit log filtering.
 */
export function useSuperAdminIdentifiers(enabled = true) {
  const [identifiers, setIdentifiers] = useState<Set<string>>(cachedSuperAdminIdentifiers || new Set());
  const [loading, setLoading] = useState(!cachedSuperAdminIdentifiers);

  useEffect(() => {
    if (!enabled) return;

    let mounted = true;
    fetchSuperAdminIdentifiers().then((set) => {
      if (mounted) {
        setIdentifiers(set);
        setLoading(false);
      }
    });

    return () => {
      mounted = false;
    };
  }, [enabled]);

  const isSuperAdminIdentifier = (identifier?: string | null): boolean => {
    if (!identifier) return false;
    return identifiers.has(identifier.trim().toLowerCase());
  };

  return {
    superAdminIdentifiers: identifiers,
    isSuperAdminIdentifier,
    isLoadingIdentifiers: loading,
  };
}
