import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                inter: ['var(--font-inter)', 'sans-serif'],
                playfair: ['var(--font-playfair)', 'serif'],
            },
            fontSize: {
                'xs': 'var(--text-size-sm)',
                'sm': 'var(--text-size-md)',
                'base': 'var(--text-size-base)',
                'lg': 'var(--text-size-lg)',
                'xl': 'var(--text-size-xl)',
                '2xl': 'var(--text-size-2xl)',
                '3xl': 'var(--text-size-3xl)',
            },
            lineHeight: {
                'tight': 'var(--text-line-height-tight)',
                'normal': 'var(--text-line-height-normal)',
                'relaxed': 'var(--text-line-height-relaxed)',
            },
            fontWeight: {
                'normal': 'var(--text-weight-regular)',
                'medium': 'var(--text-weight-medium)',
                'semibold': 'var(--text-weight-semibold)',
                'bold': 'var(--text-weight-bold)',
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "gradient-conic":
                    "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
            },
            colors: {
                "background": "var(--background)",
                "foreground": "var(--foreground)",
                "card": "var(--card)",
                "card-foreground": "var(--card-foreground)",
                "popover": "var(--popover)",
                "popover-foreground": "var(--popover-foreground)",
                "primary": "var(--primary)",
                "primary-foreground": "var(--primary-foreground)",
                "secondary": "var(--secondary)",
                "secondary-foreground": "var(--secondary-foreground)",
                "muted": "var(--muted)",
                "muted-foreground": "var(--muted-foreground)",
                "accent": "var(--accent)",
                "accent-foreground": "var(--accent-foreground)",
                "destructive": "var(--destructive)",
                "border": "var(--border)",
                "input": "var(--input)",
                "ring": "var(--ring)",
                "sidebar": "var(--sidebar)",
                "sidebar-foreground": "var(--sidebar-foreground)",
                "sidebar-primary": "var(--sidebar-primary)",
                "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
                "sidebar-accent": "var(--sidebar-accent)",
                "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
                "sidebar-border": "var(--sidebar-border)",
                "dr-bg-page": "var(--dr-bg-page)",
                "dr-bg-card": "var(--dr-bg-card)",
                "dr-bg-blue": "var(--dr-bg-blue)",
                "dr-bg-green": "var(--dr-bg-green)",
                "dr-bg-yellow": "var(--dr-bg-yellow)",
                "dr-bg-icon": "var(--dr-bg-icon)",
                "dr-primary": "var(--dr-primary)",
                "dr-primary-toggle": "var(--dr-primary-toggle)",
                "dr-text-primary": "var(--dr-text-primary)",
                "dr-text-secondary": "var(--dr-text-secondary)",
                "dr-text-muted": "var(--dr-text-muted)",
                "dr-green": "var(--dr-green)",
                "dr-yellow": "var(--dr-yellow)",
                "dr-border": "var(--dr-border)",
                "dr-border-light": "var(--dr-border-light)",
                "skin-tone-1": "var(--skin-tone-1)",
                "skin-tone-2": "var(--skin-tone-2)",
                "skin-tone-3": "var(--skin-tone-3)",
                "skin-tone-4": "var(--skin-tone-4)",
                "success-light": "var(--success-light)",
                "success-text": "var(--success-text)",
                "text-secondary": "var(--text-secondary)",
            },
        },
    },
    plugins: [],
};
export default config;
