using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WebApp.Models.DatabaseModels;

public class InvestorMatch
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string CompanyId { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string InvestorId { get; set; }

    public int MatchScore { get; set; } // 0-100

    public string Status { get; set; } = "new"; // new | viewed | interested | reviewing | matched | accepted | rejected | passed

    // ----- Bilateral True Double Opt-In -----
    public string EntrepreneurInterest { get; set; } = "new"; // new | viewed | interested | passed
    public string InvestorInterest { get; set; } = "new"; // new | interested | passed
    public DateTime? HandshakeConfirmedAt { get; set; }

    // ----- Meeting Scheduling -----
    public InvestorMeetingRecord? ScheduledMeeting { get; set; }

    // ----- Phase 7 Intelligence Snapshot -----
    public Phase7MatchingIntelligence? Phase7IntelligenceSnapshot { get; set; }

    public InvestorPreferences InvestorPreferences { get; set; } = new();

    public List<InteractionRecord> Interactions { get; set; } = new();

    /// <summary>
    /// Nullable on purpose: a missing/zero default would mask malformed rows
    /// against the validator's freshness gate. Only set by the matcher when a
    /// real row is produced; <see cref="ValidatePhase8Async"/> rejects rows
    /// where this is null.
    /// </summary>
    public DateTime? MatchedAt { get; set; }
    public DateTime? LastInteractionAt { get; set; }
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Deterministic human-readable explanation of which scoring dimensions
    /// hit/missed for this investor. Built at scoring time by
    /// <c>InvestorMatcher.CalculateMatchScoreAsync</c>. NOT generated by an
    /// LLM today — when an LLM is wired in, this field can carry the model's
    /// personalised rationale (see FUTURE-LLM TODOs in InvestorMatcher.cs).
    /// </summary>
    public string MatchRationale { get; set; }

    /// <summary>
    /// Identifies the engine that produced this match. "rule_based_v1" today;
    /// pinned to the OpenRouter model id (e.g. "openai/gpt-oss-20b:free") when an
    /// LLM matcher is wired up.
    /// </summary>
    public string EngineVersion { get; set; } = "rule_based_v1";

    public DateTime? SavedAt { get; set; }
    public DateTime? AcceptedAt { get; set; }
    public DateTime? RejectedAt { get; set; }

    /// <summary>
    /// Real component scores persisted from InvestorMatcher.ScoreAndExplain().
    /// These are the actual dimension weights used in the calculation, NOT derived
    /// or fabricated from the total. Every consumer (API, UI) reads from this
    /// single source of truth.
    /// </summary>
    public ScoreComponents ScoreComponents { get; set; } = new();

    // ----- Immutable investor snapshot (P0-3) -----
    // Captured at match creation time so cards never render with null fields
    // even if the live Investor record is later deleted or mutated. Read first
    // by GetMatchedInvestorsAsync; the live Investor record is only consulted
    // for backfill on legacy rows.
    public string InvestorNameSnapshot { get; set; }
    public string InvestorTypeSnapshot { get; set; }
    public string InvestmentRangeSnapshot { get; set; }
    public List<string> PreferredSectorsSnapshot { get; set; } = new();
}

public class InvestorPreferences
{
    public List<string> PreferredSectors { get; set; } = new();
    public List<string> PreferredStages { get; set; } = new(); // pre_seed, seed, series_a
    public double MinInvestmentAmount { get; set; }
    public double MaxInvestmentAmount { get; set; }
    public List<string> PreferredGeographies { get; set; } = new();
    public bool PreRataRightsRequired { get; set; }
    public bool BoardSeatRequired { get; set; }
}

public class ScoreComponents
{
    /// <summary>Sector match: 0-25. Company.Industry ∩ Investor.PreferredSectors.</summary>
    public int SectorScore { get; set; }

    /// <summary>Funding stage match: 0-15. Company.FundingRoundType ∩ Investor.PreferredStages.</summary>
    public int StageScore { get; set; }

    /// <summary>Check-size band fit: 0-20. Company.FundingAskAmount in [Min,Max] CheckSize range.</summary>
    public int CheckSizeScore { get; set; }

    /// <summary>Geography match: 0-10. Company.Country ∩ Investor.PreferredGeographies.</summary>
    public int GeographyScore { get; set; }

    /// <summary>Equity type match: 0-5. Company.ShareType ∩ Investor.PreferredEquityTypes.</summary>
    public int EquityTypeScore { get; set; }

    /// <summary>Investment history fit: 0-10. Investor's track record (exits, deals, activity, check size alignment).</summary>
    public int InvestmentHistoryScore { get; set; }

    /// <summary>Revenue stage alignment: 0-7. Derived from Q-total revenue against investor stage preference.</summary>
    public int RevenueStageScore { get; set; }

    /// <summary>Market size band: 0-4. Companies.MarketSizeEstimate.</summary>
    public int MarketSizeScore { get; set; }

    /// <summary>Growth potential: 0-4. Companies.GrowthPotentialScore mapped to 0-100 scale.</summary>
    public int GrowthPotentialScore { get; set; }
}

public class InteractionRecord
{
    public string Type { get; set; } // view | message | call | proposal_sent | term_sheet
    public string Details { get; set; }
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    public string InitiatedBy { get; set; } // company | investor
}

public class InvestorMeetingRecord
{
    public string MeetingId { get; set; } = ObjectId.GenerateNewId().ToString();
    public DateTime StartsAt { get; set; }
    public int DurationMinutes { get; set; } = 30;
    public string Timezone { get; set; } = "UTC";
    public string MeetingType { get; set; } = "video"; // video | call | in_person
    public string Note { get; set; } = string.Empty;
    public string Status { get; set; } = "confirmed"; // proposed | confirmed | cancelled
    public string CreatedBy { get; set; } = "entrepreneur"; // entrepreneur | investor
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}

