using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WebApp.Models.DatabaseModels;

public class InvestorMatch
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string CompanyId { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string InvestorId { get; set; }

    public int MatchScore { get; set; } // 0-100

    public string Status { get; set; } = "new"; // new | viewed | interested | reviewing | matched | rejected | passed

    public InvestorPreferences InvestorPreferences { get; set; } = new();

    public List<InteractionRecord> Interactions { get; set; } = new();

    /// <summary>
    /// Nullable on purpose: a missing/zero default would mask malformed rows
    /// against the validator's freshness gate. Only set by the matcher when a
    /// real row is produced; <see cref="ValidatePhase8Async"/> rejects rows
    /// where this is null.
    /// </summary>
    public DateTime? MatchedAt { get; set; }
    public DateTime? LastInteractionAt { get; set; }
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Deterministic human-readable explanation of which scoring dimensions
    /// hit/missed for this investor. Built at scoring time by
    /// <c>InvestorMatcher.CalculateMatchScoreAsync</c>. NOT generated by an
    /// LLM today — when an LLM is wired in, this field can carry the model's
    /// personalised rationale (see FUTURE-LLM TODOs in InvestorMatcher.cs).
    /// </summary>
    public string MatchRationale { get; set; }

    /// <summary>
    /// Identifies the engine that produced this match. "rule_based_v1" today;
    /// pinned to e.g. "claude-opus-4-7" when an LLM matcher is wired up.
    /// </summary>
    public string EngineVersion { get; set; } = "rule_based_v1";

    public DateTime? SavedAt { get; set; }
    public DateTime? AcceptedAt { get; set; }
    public DateTime? RejectedAt { get; set; }

    // ----- Immutable investor snapshot (P0-3) -----
    // Captured at match creation time so cards never render with null fields
    // even if the live Investor record is later deleted or mutated. Read first
    // by GetMatchedInvestorsAsync; the live Investor record is only consulted
    // for backfill on legacy rows.
    public string InvestorNameSnapshot { get; set; }
    public string InvestorTypeSnapshot { get; set; }
    public string InvestmentRangeSnapshot { get; set; }
    public List<string> PreferredSectorsSnapshot { get; set; } = new();
}

public class InvestorPreferences
{
    public List<string> PreferredSectors { get; set; } = new();
    public List<string> PreferredStages { get; set; } = new(); // pre_seed, seed, series_a
    public double MinInvestmentAmount { get; set; }
    public double MaxInvestmentAmount { get; set; }
    public List<string> PreferredGeographies { get; set; } = new();
    public bool PreRataRightsRequired { get; set; }
    public bool BoardSeatRequired { get; set; }
}

public class InteractionRecord
{
    public string Type { get; set; } // view | message | call | proposal_sent | term_sheet
    public string Details { get; set; }
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    public string InitiatedBy { get; set; } // company | investor
}
