export interface ContractTerms { price: number; currency: string; pricingType: string; deliveryTimeValue: number; deliveryTimeUnit: string; deliveryDayType: string; deliveryStartRule: string; includedRevisionCount: number; unlimitedRevisions: boolean; revisionRequestWindowDays: number; deliverables: string[]; allowsParallelMilestones: boolean; hourlyRate?: number | null; weeklyHourLimit?: number | null }
export interface Engagement { id: string; proposalId: string; providerId: string; clientId: string; contractId: string; title: string; description: string; contractValue: number; currency: string; startDate?: string | null; expectedEndDate?: string | null; actualEndDate?: string | null; completionPercentage: number; engagementStatus: string; escrowStatus: string; updatedAt: string }
export interface Contract { id: string; terms: ContractTerms; providerSignedAt?: string | null; clientSignedAt?: string | null; status: string; simpleConsentStub: boolean }
export interface Milestone { id: string; title: string; description: string; amount: number; currency: string; displayOrder: number; startDate?: string | null; dueDate?: string | null; completionCriteria: string; remainingRevisions: number; unlimitedRevisions: boolean; status: string; escrowStatus: string; deliveryClockState: string; reviewWindowEndsAt?: string | null; autoReleaseAt?: string | null }
export interface Deliverable { id: string; milestoneId: string; title: string; description: string; version: string; fileIds: string[]; externalLinks: string[]; submissionMessage: string; clientInstructions: string; submittedAt: string; deliverableStatus: string }
export interface RevisionRequest { id: string; milestoneId: string; deliverableId: string; description: string; requestedChanges: string[]; dueDate?: string | null; scopeClassification: string; revisionRequestStatus: string }
export interface WorkroomTask { id: string; title: string; description: string; dueDate?: string | null; visibility: string; status: string }
export interface ClientInput { id: string; type: string; description: string; dueDate?: string | null; deliveryImpact: string; status: string }
export interface WorkroomDetail { engagement: Engagement; contract: Contract; milestones: Milestone[]; deliverables: Deliverable[]; revisionRequests: RevisionRequest[]; tasks: WorkroomTask[]; clientInputRequests: ClientInput[] }
export interface FinancialTransaction { id: string; engagementId?: string; milestoneId?: string | null; grossAmount: number; currency: string; commissionAmount: number; netAmount: number; transactionType: string; paymentStatus: string; createdAt: string; releasedAt?: string | null }
export interface PayoutMethod { id: string; rail: string; displayName: string; maskedDescriptor: string; verified: boolean }
export interface FinancialSettings { payoutMethods: PayoutMethod[]; defaultPayoutMethodId?: string | null; accountOnHold: boolean; minimumPayoutAmount: number; tax: { legalName?: string; countryCode?: string; taxIdentifierMasked?: string | null; vatRegistered: boolean; vatNumberMasked?: string | null } }
export interface Payout { id: string; amount: number; currency: string; status: string; createdAt: string; completedAt?: string | null }
export interface Invoice { id: string; invoiceNumber: string; grossAmount: number; commissionAmount: number; netAmount: number; currency: string; status: string; createdAt: string }
export interface FinancialSummary { workInProgress: number; inReview: number; pending: number; available: number; withdrawn: number; onHold: number; protectedEscrow: number; currency: string; transactions: FinancialTransaction[]; payouts: Payout[]; invoices: Invoice[]; settings: FinancialSettings }
export interface SubmitDeliverablePayload { title: string; description: string; fileIds: string[]; externalLinks: string[]; submissionMessage: string; clientInstructions: string; allDeliverablesIncluded: boolean; filesReviewed: boolean; noUnrelatedPrivateInfo: boolean; readyForReview: boolean; majorScopeVersion: boolean }
